[project]
name = "mitadtu-docking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.0.2",
    "pandas>=2.3.1",
]
